name:                desktop-portal
version:             0.1.0.0
license:             MIT
synopsis:            Desktop Portal.
description:         A Haskell wrapper for the XDG Desktop Portal DBUS API.
github:              Dretch/haskell-desktop-portal
homepage:            https://github.com/Dretch/haskell-desktop-portal#readme
bug-reports:         https://github.com/Dretch/haskell-desktop-portal/issues
category:            GUI, XDG, Flatpak, Desktop, Portal
maintainer:          garethdanielsmith@gmail.com

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- data-default-class
- dbus >= 1.2.28 && < 1.3
- random
- text

default-extensions:
- DisambiguateRecordFields
- DuplicateRecordFields
- FlexibleContexts
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- NoFieldSelectors
- NumericUnderscores
- OverloadedRecordDot
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TupleSections

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Desktop.Portal
  - Desktop.Portal.Account
  - Desktop.Portal.FileChooser
  - Desktop.Portal.Notification

tests:
  spec:
    defaults: hspec/hspec@master
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
    - desktop-portal
    - process